apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot-output
  labels:
    app: moonshot-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot-output
  template:
    metadata:
      labels:
        app: moonshot-output
    spec:
      containers:
      - name: moonshot-output
        image: scr.io/moonshot-samples-output:latest
        volumeMounts:
          - mountPath: /app/Configuration
            name: config
          - mountPath: /app/secrets
            name: secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: output-configuration
          items:
          - key: "config.tags"
            path: configuration.yml
      - name: secrets
        secret:
          secretName: output-connection-string
